name: Conuter caller

on:
  workflow_dispatch:
  
jobs:
  invoke-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/github-script@v6
        with:
          script: |
            console.log('Deploying to production server on branch $GITHUB_REF');
            console.log('${{ github.workspace }}/counter.js');
            const { counter } = require('${{ github.workspace }}/counter.js');
            const countResult = counter();
            console.log('Counter result:', countResult);
