name: Repository Dispatch Workflow

on:
  repository_dispatch:
    types: [build-event, test-event]

jobs:
  repository-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event
        run: |
          echo "PlayLoad: ${{ toJSON(github.event) }}"
        
      - name: Run build step
        if: github.event.action == 'build-event'
        run: |
          echo "Running build step..."
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          # 在這裡添加您的構建步驟

      - name: Run test step
        if: github.event.action == 'test-event'
        run: |
          echo "Running test step..."
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          # 在這裡添加您的測試步驟
