name: Run Script

on: 
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: List dir
        run: ls -al
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List dir 2
        run: ls -al .github/script/
      - name: Run build script
        run: |
          chmod +x ./.github/script/hello-world.sh
          ./.github/script/hello-world.sh
